### ISSUE TITLE
Library not uploading

### ISSUE THREAD

**Issue by SnakeScience** [visakhanc/eCompass#1]
Whenever I try and add in the zip folder, the fabled "Specified folder/zip file does not contain a valid library" comment appears on the bottom screen. Is there a reason for this and how do I get around it? Thank you.

**Comment by visakhanc** [comment]
This project is not meant for compilation using arduino IDE. This is project need to be compiled using simple _make_  command in command line, or using IDEs like eclipse. Please see the Readme of this project.
